/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interface from "./interface";
export type { interface };
export type { Add3Token } from "./Add3Token";
export type { Staking } from "./Staking";
