/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interface from "./interface";
export { Add3Token__factory } from "./Add3Token__factory";
export { Staking__factory } from "./Staking__factory";
